apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-consumer-test2
  # Optional: Specify the namespace if your consumer isn't in the 'default' namespace
  # namespace: your-consumer-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion-consumer-test2
  template:
    metadata:
      labels:
        app: ingestion-consumer-test2
    spec:
      containers:
        - name: ingestion-consumer
          # Make sure this image is accessible from your Kubernetes cluster
          image: datalake/ingestion:latest
          imagePullPolicy: IfNotPresent # Or Always if needed
          env:
            - name: KAFKA_BROKERS
              # Use the comma-separated list of broker DNS names from the headless service
              value: "kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092,kafka-2.kafka-headless.kafka.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "raw_test2" # Ensure this topic exists in your Kafka cluster
            - name: KAFKA_GROUP_ID
              value: "ingestion-consumers-test2"
            - name: SCHEMA_REGISTRY_HOST
              value: "schema-registry.default.svc.cluster.local"
            - name: SCHEMA_REGISTRY_PORT
              value: "8081"
            - name: MASTER_SERVICE_PORT
              value: "50055"
          # Add resource requests/limits for better pod scheduling
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
