apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-ingestion
  template:
    metadata:
      labels:
        app: streaming-ingestion
    spec:
      containers:
        - name: streaming-ingestion
          image: streaming_ingestion:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              value: "kafka-headless.kafka.svc.cluster.local:9092"     
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-ingestion
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: streaming-ingestion
