apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-postgres
  template:
    metadata:
      labels:
        app: identity-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-postgres-secret
                  key: postgres-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: identity-postgres-secret
                  key: postgres-user
            # The PGDATA variable is not strictly necessary when using the default path
          volumeMounts:
            - name: postgres-storage # Use an emptyDir volume mount
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {} # Use a temporary emptyDir volume
