apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: datalake/identity:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
            - containerPort: 50056
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082
    - name: grpc
      port: 50055
      targetPort: 50056
      nodePort: 30055
  selector:
    app: identity-service
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-postgres-secret
type: Opaque
data:
  postgres-password: aWRlbnRpdHlwYXNzd29yZA== # identitypassword
  postgres-user: aWRlbnRpdHl1c2Vy # identityuser
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-postgres
  template:
    metadata:
      labels:
        app: identity-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-postgres-secret
                  key: postgres-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: identity-postgres-secret
                  key: postgres-user
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: identity-postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: identity-postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: identity-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: identity-postgres
