apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-tests
  labels:
    app: integration-tests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-tests
  template:
    metadata:
      labels:
        app: integration-tests
    spec:
      containers:
        - name: integration-tests
          image: datalake/integration_tests:latest
