apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema_registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema_registry
  template:
    metadata:
      labels:
        app: schema_registry
    spec:
      containers:
        - name: schema_registry
          image: schema_registry:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
            
---
apiVersion: v1
kind: Service
metadata:
  name: schema_registry
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: schema_registry
