apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: {{ .Values.master.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.master.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.master.port }}
      targetPort: {{ .Values.master.port }}
  selector:
    app: master
