apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "default-service-account" }}
{{- if .Values.serviceAccount.create }}
automountServiceAccountToken: true
{{- end }}