{{- range .Values.workers.nodes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: worker
          image: {{ $.Values.workers.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .port }}
          env:
            - name: GRPC_PORT
              value: ":{{ .port }}"
          volumeMounts:
            - name: worker-state-storage
              mountPath: /data
      volumes:
        - name: worker-state-storage
          persistentVolumeClaim:
            claimName: {{ .pvc }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
  selector:
    app: {{ .name }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .pv }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: {{ .path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .pvc }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: {{ .pv }}
  storageClassName: standard
{{- end }}
