apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker1-state-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # <-- Added
  hostPath:
    path: /datalake/worker_data/worker1-state
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker2-state-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # <-- Added
  hostPath:
    path: /datalake/worker_data/worker2-state
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker3-state-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # <-- Added
  hostPath:
    path: /datalake/worker_data/worker3-state
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker1-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: worker1-state-pv
  storageClassName: standard  # <-- Added
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker2-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: worker2-state-pv
  storageClassName: standard  # <-- Added
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker3-state-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: worker3-state-pv
  storageClassName: standard  # <-- Added
