// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: lb.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUID) Reset() {
	*x = UUID{}
	mi := &file_lb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUID) ProtoMessage() {}

func (x *UUID) ProtoReflect() protoreflect.Message {
	mi := &file_lb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUID.ProtoReflect.Descriptor instead.
func (*UUID) Descriptor() ([]byte, []int) {
	return file_lb_proto_rawDescGZIP(), []int{0}
}

func (x *UUID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type WorkerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerIDRequest) Reset() {
	*x = WorkerIDRequest{}
	mi := &file_lb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerIDRequest) ProtoMessage() {}

func (x *WorkerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerIDRequest.ProtoReflect.Descriptor instead.
func (*WorkerIDRequest) Descriptor() ([]byte, []int) {
	return file_lb_proto_rawDescGZIP(), []int{1}
}

type WorkerIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      *UUID                  `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerIDResponse) Reset() {
	*x = WorkerIDResponse{}
	mi := &file_lb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerIDResponse) ProtoMessage() {}

func (x *WorkerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerIDResponse.ProtoReflect.Descriptor instead.
func (*WorkerIDResponse) Descriptor() ([]byte, []int) {
	return file_lb_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerIDResponse) GetWorkerId() *UUID {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

var File_lb_proto protoreflect.FileDescriptor

var file_lb_proto_rawDesc = string([]byte{
	0x0a, 0x08, 0x6c, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x62, 0x5f, 0x64,
	0x66, 0x73, 0x22, 0x1c, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x11, 0x0a, 0x0f, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x62, 0x5f,
	0x64, 0x66, 0x73, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x49, 0x64, 0x32, 0x4d, 0x0a, 0x09, 0x4c, 0x42, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x40, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x12, 0x17,
	0x2e, 0x6c, 0x62, 0x5f, 0x64, 0x66, 0x73, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x44,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x62, 0x5f, 0x64, 0x66, 0x73,
	0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x72, 0x61, 0x7a, 0x76, 0x61, 0x6e, 0x6d, 0x61, 0x72, 0x69, 0x6e, 0x6e, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x6c, 0x61, 0x6b, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_lb_proto_rawDescOnce sync.Once
	file_lb_proto_rawDescData []byte
)

func file_lb_proto_rawDescGZIP() []byte {
	file_lb_proto_rawDescOnce.Do(func() {
		file_lb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lb_proto_rawDesc), len(file_lb_proto_rawDesc)))
	})
	return file_lb_proto_rawDescData
}

var file_lb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lb_proto_goTypes = []any{
	(*UUID)(nil),             // 0: lb_dfs.UUID
	(*WorkerIDRequest)(nil),  // 1: lb_dfs.WorkerIDRequest
	(*WorkerIDResponse)(nil), // 2: lb_dfs.WorkerIDResponse
}
var file_lb_proto_depIdxs = []int32{
	0, // 0: lb_dfs.WorkerIDResponse.worker_id:type_name -> lb_dfs.UUID
	1, // 1: lb_dfs.LBService.GetWorkerID:input_type -> lb_dfs.WorkerIDRequest
	2, // 2: lb_dfs.LBService.GetWorkerID:output_type -> lb_dfs.WorkerIDResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lb_proto_init() }
func file_lb_proto_init() {
	if File_lb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lb_proto_rawDesc), len(file_lb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lb_proto_goTypes,
		DependencyIndexes: file_lb_proto_depIdxs,
		MessageInfos:      file_lb_proto_msgTypes,
	}.Build()
	File_lb_proto = out.File
	file_lb_proto_goTypes = nil
	file_lb_proto_depIdxs = nil
}
