// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: master.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterService_RegisterFile_FullMethodName        = "/master_dfs.MasterService/RegisterFile"
	MasterService_GetBatchDestination_FullMethodName = "/master_dfs.MasterService/GetBatchDestination"
	MasterService_GetMetadata_FullMethodName         = "/master_dfs.MasterService/GetMetadata"
)

// MasterServiceClient is the client API for MasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterServiceClient interface {
	RegisterFile(ctx context.Context, in *ClientFileRequestToMaster, opts ...grpc.CallOption) (*MasterFileResponse, error)
	GetBatchDestination(ctx context.Context, in *ClientBatchRequestToMaster, opts ...grpc.CallOption) (*MasterResponse, error)
	GetMetadata(ctx context.Context, in *Location, opts ...grpc.CallOption) (*MasterMetadataResponse, error)
}

type masterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterServiceClient(cc grpc.ClientConnInterface) MasterServiceClient {
	return &masterServiceClient{cc}
}

func (c *masterServiceClient) RegisterFile(ctx context.Context, in *ClientFileRequestToMaster, opts ...grpc.CallOption) (*MasterFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MasterFileResponse)
	err := c.cc.Invoke(ctx, MasterService_RegisterFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) GetBatchDestination(ctx context.Context, in *ClientBatchRequestToMaster, opts ...grpc.CallOption) (*MasterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MasterResponse)
	err := c.cc.Invoke(ctx, MasterService_GetBatchDestination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) GetMetadata(ctx context.Context, in *Location, opts ...grpc.CallOption) (*MasterMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MasterMetadataResponse)
	err := c.cc.Invoke(ctx, MasterService_GetMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServiceServer is the server API for MasterService service.
// All implementations must embed UnimplementedMasterServiceServer
// for forward compatibility.
type MasterServiceServer interface {
	RegisterFile(context.Context, *ClientFileRequestToMaster) (*MasterFileResponse, error)
	GetBatchDestination(context.Context, *ClientBatchRequestToMaster) (*MasterResponse, error)
	GetMetadata(context.Context, *Location) (*MasterMetadataResponse, error)
	mustEmbedUnimplementedMasterServiceServer()
}

// UnimplementedMasterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterServiceServer struct{}

func (UnimplementedMasterServiceServer) RegisterFile(context.Context, *ClientFileRequestToMaster) (*MasterFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterFile not implemented")
}
func (UnimplementedMasterServiceServer) GetBatchDestination(context.Context, *ClientBatchRequestToMaster) (*MasterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatchDestination not implemented")
}
func (UnimplementedMasterServiceServer) GetMetadata(context.Context, *Location) (*MasterMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (UnimplementedMasterServiceServer) mustEmbedUnimplementedMasterServiceServer() {}
func (UnimplementedMasterServiceServer) testEmbeddedByValue()                       {}

// UnsafeMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServiceServer will
// result in compilation errors.
type UnsafeMasterServiceServer interface {
	mustEmbedUnimplementedMasterServiceServer()
}

func RegisterMasterServiceServer(s grpc.ServiceRegistrar, srv MasterServiceServer) {
	// If the following call pancis, it indicates UnimplementedMasterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterService_ServiceDesc, srv)
}

func _MasterService_RegisterFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientFileRequestToMaster)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).RegisterFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_RegisterFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).RegisterFile(ctx, req.(*ClientFileRequestToMaster))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_GetBatchDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientBatchRequestToMaster)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).GetBatchDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_GetBatchDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).GetBatchDestination(ctx, req.(*ClientBatchRequestToMaster))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_GetMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).GetMetadata(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterService_ServiceDesc is the grpc.ServiceDesc for MasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "master_dfs.MasterService",
	HandlerType: (*MasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterFile",
			Handler:    _MasterService_RegisterFile_Handler,
		},
		{
			MethodName: "GetBatchDestination",
			Handler:    _MasterService_GetBatchDestination_Handler,
		},
		{
			MethodName: "GetMetadata",
			Handler:    _MasterService_GetMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}

const (
	LBService_GetWorkerID_FullMethodName = "/master_dfs.LBService/GetWorkerID"
)

// LBServiceClient is the client API for LBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LBServiceClient interface {
	GetWorkerID(ctx context.Context, in *WorkerIDRequest, opts ...grpc.CallOption) (*WorkerIDResponse, error)
}

type lBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLBServiceClient(cc grpc.ClientConnInterface) LBServiceClient {
	return &lBServiceClient{cc}
}

func (c *lBServiceClient) GetWorkerID(ctx context.Context, in *WorkerIDRequest, opts ...grpc.CallOption) (*WorkerIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkerIDResponse)
	err := c.cc.Invoke(ctx, LBService_GetWorkerID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LBServiceServer is the server API for LBService service.
// All implementations must embed UnimplementedLBServiceServer
// for forward compatibility.
type LBServiceServer interface {
	GetWorkerID(context.Context, *WorkerIDRequest) (*WorkerIDResponse, error)
	mustEmbedUnimplementedLBServiceServer()
}

// UnimplementedLBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLBServiceServer struct{}

func (UnimplementedLBServiceServer) GetWorkerID(context.Context, *WorkerIDRequest) (*WorkerIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkerID not implemented")
}
func (UnimplementedLBServiceServer) mustEmbedUnimplementedLBServiceServer() {}
func (UnimplementedLBServiceServer) testEmbeddedByValue()                   {}

// UnsafeLBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LBServiceServer will
// result in compilation errors.
type UnsafeLBServiceServer interface {
	mustEmbedUnimplementedLBServiceServer()
}

func RegisterLBServiceServer(s grpc.ServiceRegistrar, srv LBServiceServer) {
	// If the following call pancis, it indicates UnimplementedLBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LBService_ServiceDesc, srv)
}

func _LBService_GetWorkerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LBServiceServer).GetWorkerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LBService_GetWorkerID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LBServiceServer).GetWorkerID(ctx, req.(*WorkerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LBService_ServiceDesc is the grpc.ServiceDesc for LBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "master_dfs.LBService",
	HandlerType: (*LBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkerID",
			Handler:    _LBService_GetWorkerID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
