// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: metadata_service.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_VerifyProjectExistence_FullMethodName    = "/metadata_service.MetadataService/VerifyProjectExistence"
	MetadataService_GetCompactionJob_FullMethodName          = "/metadata_service.MetadataService/GetCompactionJob"
	MetadataService_UpdateCompactionJobStatus_FullMethodName = "/metadata_service.MetadataService/UpdateCompactionJobStatus"
	MetadataService_RegisterBlock_FullMethodName             = "/metadata_service.MetadataService/RegisterBlock"
	MetadataService_GetBlockLocations_FullMethodName         = "/metadata_service.MetadataService/GetBlockLocations"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataServiceClient interface {
	VerifyProjectExistence(ctx context.Context, in *VerifyProjectExistenceRequest, opts ...grpc.CallOption) (*VerifyProjectExistenceResponse, error)
	// Compaction Job Management
	GetCompactionJob(ctx context.Context, in *GetCompactionJobRequest, opts ...grpc.CallOption) (*GetCompactionJobResponse, error)
	UpdateCompactionJobStatus(ctx context.Context, in *UpdateCompactionJobStatusRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	// Block Management
	RegisterBlock(ctx context.Context, in *RegisterBlockRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	GetBlockLocations(ctx context.Context, in *GetBlockLocationsRequest, opts ...grpc.CallOption) (*GetBlockLocationsResponse, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) VerifyProjectExistence(ctx context.Context, in *VerifyProjectExistenceRequest, opts ...grpc.CallOption) (*VerifyProjectExistenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyProjectExistenceResponse)
	err := c.cc.Invoke(ctx, MetadataService_VerifyProjectExistence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetCompactionJob(ctx context.Context, in *GetCompactionJobRequest, opts ...grpc.CallOption) (*GetCompactionJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompactionJobResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetCompactionJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) UpdateCompactionJobStatus(ctx context.Context, in *UpdateCompactionJobStatusRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, MetadataService_UpdateCompactionJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) RegisterBlock(ctx context.Context, in *RegisterBlockRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, MetadataService_RegisterBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetBlockLocations(ctx context.Context, in *GetBlockLocationsRequest, opts ...grpc.CallOption) (*GetBlockLocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockLocationsResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetBlockLocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
type MetadataServiceServer interface {
	VerifyProjectExistence(context.Context, *VerifyProjectExistenceRequest) (*VerifyProjectExistenceResponse, error)
	// Compaction Job Management
	GetCompactionJob(context.Context, *GetCompactionJobRequest) (*GetCompactionJobResponse, error)
	UpdateCompactionJobStatus(context.Context, *UpdateCompactionJobStatusRequest) (*SimpleResponse, error)
	// Block Management
	RegisterBlock(context.Context, *RegisterBlockRequest) (*SimpleResponse, error)
	GetBlockLocations(context.Context, *GetBlockLocationsRequest) (*GetBlockLocationsResponse, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) VerifyProjectExistence(context.Context, *VerifyProjectExistenceRequest) (*VerifyProjectExistenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyProjectExistence not implemented")
}
func (UnimplementedMetadataServiceServer) GetCompactionJob(context.Context, *GetCompactionJobRequest) (*GetCompactionJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCompactionJob not implemented")
}
func (UnimplementedMetadataServiceServer) UpdateCompactionJobStatus(context.Context, *UpdateCompactionJobStatusRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompactionJobStatus not implemented")
}
func (UnimplementedMetadataServiceServer) RegisterBlock(context.Context, *RegisterBlockRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBlock not implemented")
}
func (UnimplementedMetadataServiceServer) GetBlockLocations(context.Context, *GetBlockLocationsRequest) (*GetBlockLocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockLocations not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_VerifyProjectExistence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyProjectExistenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).VerifyProjectExistence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_VerifyProjectExistence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).VerifyProjectExistence(ctx, req.(*VerifyProjectExistenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetCompactionJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompactionJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetCompactionJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetCompactionJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetCompactionJob(ctx, req.(*GetCompactionJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_UpdateCompactionJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompactionJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).UpdateCompactionJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_UpdateCompactionJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).UpdateCompactionJobStatus(ctx, req.(*UpdateCompactionJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_RegisterBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).RegisterBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_RegisterBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).RegisterBlock(ctx, req.(*RegisterBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetBlockLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetBlockLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetBlockLocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetBlockLocations(ctx, req.(*GetBlockLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metadata_service.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyProjectExistence",
			Handler:    _MetadataService_VerifyProjectExistence_Handler,
		},
		{
			MethodName: "GetCompactionJob",
			Handler:    _MetadataService_GetCompactionJob_Handler,
		},
		{
			MethodName: "UpdateCompactionJobStatus",
			Handler:    _MetadataService_UpdateCompactionJobStatus_Handler,
		},
		{
			MethodName: "RegisterBlock",
			Handler:    _MetadataService_RegisterBlock_Handler,
		},
		{
			MethodName: "GetBlockLocations",
			Handler:    _MetadataService_GetBlockLocations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metadata_service.proto",
}
