apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            # Explicitly set the endpoint to listen on all network interfaces
            # for gRPC, which is the default OTLP gRPC port.
            endpoint: 0.0.0.0:4317
          http:
            # Explicitly set the endpoint to listen on all network interfaces
            # for HTTP, which is the default OTLP HTTP port.
            endpoint: 0.0.0.0:4318

    exporters:
      # This 'otlp' exporter is for sending data *from* the collector
      # *to* Jaeger. Ensure Jaeger is configured to receive OTLP on 4317.
      otlp:
        endpoint: jaeger-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true # Use this only for development/testing, not production

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
