name: K8s Tests Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Minikube and kubectl
        run: |
          set -euxo pipefail
          OS_TYPE=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH_TYPE=$(uname -m)
          if [[ "${ARCH_TYPE}" == "aarch64" ]]; then
              ARCH_TYPE="arm64"
          fi
          MINIKUBE_BINARY="minikube-${OS_TYPE}-${ARCH_TYPE}"
          KUBECTL_BINARY="kubectl"
          echo "Detected OS: ${OS_TYPE}, Architecture: ${ARCH_TYPE}"
          echo "Attempting to download Minikube as: ${MINIKUBE_BINARY}"
          echo "Downloading Minikube..."
          curl -LO "https://storage.googleapis.com/minikube/releases/latest/${MINIKUBE_BINARY}"
          echo "Moving Minikube to /usr/local/bin and making it executable..."
          sudo mv "${MINIKUBE_BINARY}" /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube
          echo "Downloading kubectl..."
          KUBECTL_DOWNLOAD_URL="https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/${OS_TYPE}/${ARCH_TYPE}/${KUBECTL_BINARY}"
          curl -LO "${KUBECTL_DOWNLOAD_URL}"
          echo "Moving kubectl to /usr/local/bin and making it executable..."
          sudo mv "${KUBECTL_BINARY}" /usr/local/bin/kubectl
          sudo chmod +x /usr/local/bin/kubectl
          echo "Verifying Minikube and kubectl installations..."
          ls -l /usr/local/bin/minikube
          file /usr/local/bin/minikube
          minikube version
          ls -l /usr/local/bin/kubectl
          file /usr/local/bin/kubectl
          kubectl version --client

      - name: Setup K8s Environment (Minikube & Deploy Apps)
        run: |
          #!/bin/bash
          set -euxo pipefail
          minikube delete || true
          minikube start --driver=docker
          eval $(minikube docker-env)
          make
          sleep 10
          NAMESPACE_DATE=$(date +%Y%m%d)
          DYNAMIC_NAMESPACE="test-env-${NAMESPACE_DATE}"
          echo "Creating namespace: ${DYNAMIC_NAMESPACE}"
          kubectl create ns "${DYNAMIC_NAMESPACE}" || true
          echo "DYNAMIC_NAMESPACE=${DYNAMIC_NAMESPACE}" >> $GITHUB_ENV
          find ./k8s/test-env/ -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \) -print0 | while IFS= read -r -d $'\0' file; do
            echo "Substituting namespace in: $file"
            sed -i.bak "s|__DYNAMIC_NAMESPACE__|${DYNAMIC_NAMESPACE}|g" "$file"
            rm "${file}.bak"
          done
          echo "Applying datalake application manifests from local path to namespace: ${DYNAMIC_NAMESPACE}..."
          kubectl apply -f ./k8s/test-env/
          echo "Setup complete!"
        env:
          KUBECONFIG: ~/.kube/config

      - name: Set up Port Forwarding for Services
        run: |
          #!/bin/bash
          set -euxo pipefail

          kubectl port-forward svc/identity-service 8082:8082 -n "${DYNAMIC_NAMESPACE}" > /dev/null 2>&1 &
          echo $! >> port-forward.pid

          kubectl port-forward svc/api-gateway 8083:80 -n "${DYNAMIC_NAMESPACE}" > /dev/null 2>&1 &
          echo $! >> port-forward.pid

          echo "Port forwarding started for multiple services."
          sleep 5

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run Go Integration Tests
        run: |
          #!/bin/bash
          set -euxo pipefail
          export KUBECONFIG=~/.kube/config
          echo "Running Go integration tests..."
          cd test/integration
          go test -v ./...
        env:
          DYNAMIC_NAMESPACE: ${{ env.DYNAMIC_NAMESPACE }}

      - name: Teardown Minikube Cluster
        if: always()
        run: |
          # Kill all port-forward processes whose PIDs are stored in the file
          if [ -f port-forward.pid ]; then
            echo "Killing port-forward processes..."
            while read PID; do
              echo "Killing PID: $PID"
              kill "$PID" || true # Use || true to prevent script from failing if PID is already gone
            done < port-forward.pid
            rm port-forward.pid
          fi
          minikube delete
